<a href="https://colab.research.google.com/github/neSTORY/Deeplearning_Zero_to_All/blob/master/softmax_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [4]:
# data
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
          
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

In [10]:
# shape of output
input_shape = x_data.shape[-1]
output_shape = y_data.shape[-1]

# weight & bias
W = tf.Variable(tf.random.normal([input_shape, output_shape]), name="weight")
b = tf.Variable(tf.random.normal([output_shape]), name="bias")

In [12]:
print(W.shape)
print(b.shape)

print(W)
print(b)

(4, 3)
(3,)
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.70379466,  1.5352443 ,  0.53295094],
       [-0.73621476,  0.53179765, -0.45222577],
       [ 0.20244843, -0.41671765,  0.58190703],
       [-0.61397743, -0.09683143, -0.16439489]], dtype=float32)>
<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([ 0.8482564 ,  1.4321135 , -0.28505102], dtype=float32)>


In [14]:
# test
sample_data = [[8,2,1,4]]
sample_data = np.array(sample_data, dtype="float32")

# output
tf.math.softmax(tf.matmul(sample_data, W) + b) # 두 번째 레이블이 선택됨.

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.3390982e-05, 9.9996948e-01, 1.7120745e-05]], dtype=float32)>

In [19]:
def hypothesis(x):
  hx = tf.math.softmax(tf.matmul(x,W)+b)
  return hx

def loss_fn(x,y):
  loss = tf.reduce_mean(-tf.reduce_mean(y*tf.math.log(hypothesis(x)),axis=1))
  return loss

optimizers = tf.keras.optimizers.SGD(0.1)

def grad_fn(x, y):
  with tf.GradientTape() as tape:
    loss = loss_fn(x, y)
    grads = tape.gradient(loss, [W,b])
    return grads

In [20]:
epochs = 2000

for epoch in range(1, epochs+1):
  grads = grad_fn(x_data, y_data)
  optimizers.apply_gradients(zip(grads, [W,b]))
  if epoch % 100 == 0:
    print("epoch : {:2}, Loss : {:4.3f}".format(epoch, loss_fn(x_data, y_data)))

epoch : 100, Loss : 0.285
epoch : 200, Loss : 0.226
epoch : 300, Loss : 0.197
epoch : 400, Loss : 0.180
epoch : 500, Loss : 0.168
epoch : 600, Loss : 0.159
epoch : 700, Loss : 0.152
epoch : 800, Loss : 0.146
epoch : 900, Loss : 0.140
epoch : 1000, Loss : 0.136
epoch : 1100, Loss : 0.131
epoch : 1200, Loss : 0.127
epoch : 1300, Loss : 0.124
epoch : 1400, Loss : 0.120
epoch : 1500, Loss : 0.117
epoch : 1600, Loss : 0.114
epoch : 1700, Loss : 0.111
epoch : 1800, Loss : 0.109
epoch : 1900, Loss : 0.106
epoch : 2000, Loss : 0.104


In [25]:
print(tf.argmax(hypothesis(x_data),1))
print(tf.argmax(y_data,1))

tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


<tf.Tensor: shape=(1, 8), dtype=int64, numpy=array([[1, 2, 3, 2, 1, 3, 1, 1]])>

In [32]:
tf.argmax(x_data,0)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 4, 7, 7])>